name: Build and Push Ferrules Container

on:
  push:
    branches: [ pdftotts ]
    paths-ignore:
      - 'README.md'
      - '.github/README.md'
      - 'docs/**'
  pull_request:
    branches: [ pdftotts ]
    paths-ignore:
      - 'README.md'
      - '.github/README.md'
      - 'docs/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: joubertb/repos

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch,prefix=ferrules-
          type=ref,event=pr,prefix=ferrules-pr-
          type=sha,prefix=ferrules-{{branch}}-
          type=raw,value=ferrules-latest,enable=${{ github.ref == 'refs/heads/pdftotts' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=gha
          type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ferrules-buildcache
        cache-to: |
          type=gha,mode=max
          type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ferrules-buildcache,mode=max

    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}